### PR TITLE
Add darkmode

### PR DESCRIPTION
**Pull request by kritzl**
Optional dark mode to protect your eyes.
Activated according to system settings and can be forced on/off by a switch (setting saved in local storage).

The snow in winter is also easier to enjoy this way ❄️

### CODE REVIEW

**Review by ftsell — CHANGES_REQUESTED** [review]
image

I feel like the theme toggle icon is not correctly centered

---

Also, did you intend to add the `darkmode.scss` and `darkmode.css.map` files to git? I'm asking because we have no infrastructure in place for this repo to process these files.

**Comment by kritzl** [comment]
The Icon is as centered as the other Icons in Buttons (Groups, Settings) - nevertheless I agree that they should align better.

I personally like to have the scss file even if we have no pipeline to compile it, so future changes can be made more easily.

**Comment by timonegk** [comment]
For now, I think it is okay to add all the files. In the future, we should add a way to compile scss files and minify javascript. I would suggest django-pipeline.

**Review by ftsell — APPROVED** [review]

**Comment by kritzl** [comment]
> For now, I think it is okay to add all the files. In the future, we should add a way to compile scss files and minify javascript. I would suggest django-pipeline.

We should also consider enabling cache busting so that updates to the dashboard do not cause temporary errors for the user.
https://django-pipeline.readthedocs.io/en/latest/usage.html#cache-busting

**Pull request merged**
