### PR TITLE
Replace cloud icon with logo

### PR DESCRIPTION
**Pull request by jaagut**

### CODE REVIEW

**Review by ftsell — APPROVED** [review]

**Comment by hprid** [comment]
Did you consider copyright and trademark issues? Copyright might not be an issue due to missing threshold of originality but trademark may is. What is the owner's trademark policy and does your usage conform with it? The former icons were drawn from public domain images on exactly this purpose.

**Comment by timonegk** [comment]
Hm, I did not consider that. Nextcloud specifies their trademark usage here: https://nextcloud.com/trademarks/
But shouldn't a usage in the dashboard fall under Free Use?

**Comment by hprid** [comment]
The trademark policy says: “The logo is light blue (#0082c9) with white text/image. It must not be used differently, especially not inverted. The name "Nextcloud" can be optionally left out though, we provide logos without the text.”

This patch shows a black logo, i. e., not “light blue” and I would consider it to violate the “must not be used differently” of the trademark policy here.

**Comment by timonegk** [comment]
You're probably right, I reverted the commit for now. The light blue logo also does not really fit into our design.

**Pull request merged**
